"""Create table to store locations rank

Revision ID: d1adb528deca
Revises: f3bd803f741e
Create Date: 2021-09-19 13:24:38.402851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1adb528deca'
down_revision = 'f3bd803f741e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_rank',
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('frecuency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zipcode'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_rank')
    # ### end Alembic commands ###
